---

  - hosts: db
    gather_facts: yes
    become: true

# add instructions using tasks module to install mongodb
    tasks:
    - name: install mongodb
      apt: pkg=mongodb state=present


# remove default mongodb.conf file
    - name: Remove mongodb file
      file:
        path: /etc/mongodb.conf
        state: absent

# create a mongodb.conf file with required permissions
    - name: Touch a file, using symbolic modes to set the permissions ( equivalent to 0644)
      file:
        path: /etc/mongodb.conf
        state: touch
        mode: u=rw,g=r,o=r

# set up mongodb.conf with correct port and ip to allow access
    - name: Insert multiple lines and backup
      blockinfile:
        path: /etc/mongodb.conf
        block: |
          "storage:
            dbPath: /var/lib/mongodb
            journal:
              enabled: true
          systemLog:
            destination: file
            logAppend: true
            path: /var/log/mongodb/mongod.log
          net:
            port: 27017
            bindIp: 0.0.0.0"
    - name: Restart mongodb
      become: true
      shell: systemctl restart mongodb

# enable mongodb with admin access
    - name: enable mongodb
      become: true
      shell: systemctl enable mongodb
